import '../styles/globals.css';
import '../ui/assets/css/App.css';

import { ChakraProvider } from '@chakra-ui/react';
import theme from '../ui/theme/theme';
import Head from 'next/head';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>tryyon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blue_tshirt.svg" />
      </Head>
      <ChakraProvider theme={theme}>
        <Component {...pageProps} />
      </ChakraProvider>
    </>
  );
}

export default MyApp;
