import '../styles/globals.css';
import '../ui/assets/css/App.css';

import { ChakraProvider } from '@chakra-ui/react';
import theme from '../ui/theme/theme';
import Head from 'next/head';
import Navbar from './Components/Navbar';
import Logout from './Components/Logout';
import { useEffect } from 'react';
import { useState } from 'react';

function MyApp({ Component, pageProps }) {
  const [comp, setComp] = useState(0);
  useEffect(() => {
    if (
      sessionStorage.getItem('token_use') !== null ||
      sessionStorage.getItem('token_admin') !== null
    ) {
      setComp(1);
    } else {
      setComp(0);
    }
  });

  return (
    <>
      <Head>
        <title>tryyon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/blue_tshirt.svg" />
      </Head>
      {comp === 1 ? <Logout /> : <Navbar />}
      <ChakraProvider theme={theme}>
        <Component {...pageProps} />
      </ChakraProvider>
    </>
  );
}

export default MyApp;
